version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: coin_marketplace
      POSTGRES_USER: coinuser
      POSTGRES_PASSWORD: coinpass123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: coinmq
      RABBITMQ_DEFAULT_PASS: coinmq123

  elasticsearch:
    image: elasticsearch:8.13
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"

volumes:
  pgdata:
